source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MSTagTextView_Example', :exclusive => true do
  pod "MSTagTextView", :path => "../"
end

target 'MSTagTextView_Tests', :exclusive => true do
  pod "MSTagTextView", :path => "../"

  
end
